### ISSUE TITLE
Product Bundle Media Overlay Support for Sulu 1.4

### ISSUE THREAD

**Issue by turbo-ele** [sulu/SuluProductBundle#363]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Version | 0.16.5

### Original Issue by @ISC3141

Hello, thanks for your nice product bundle.
Do you know if this bug fix will be released soon?
I would like to add some media to the products but it does not work with Sulu 1.4.5 and Product Bundle 0.16.5...

https://github.com/sulu/SuluProductBundle/pull/340#issuecomment-278321856

**Comment by turbo-ele** [comment]
@ISC3141 we will create a new version 0.17.0 with the newest fixes and features.
Did you test your application with the current product-bundle's `dev-develop`? If not, could you please do so?
Thank you!

**Comment by turbo-ele** [comment]
@ISC3141 https://github.com/sulu/SuluProductBundle/releases/tag/0.17.0

**Comment by ISC3141** [comment]
Thank you, media works now!
